# Generated by Django 5.1.1 on 2025-01-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_category', models.CharField(default=0, max_length=250)),
                ('product_price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=350)),
                ('used_by', models.DateField()),
                ('image', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
    ]
