# Generated by Django 5.1.1 on 2025-01-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_net_quantity_product_number_of_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
